### ISSUE TITLE
"Cannot read property 'length' of undefined" error when there is no message is SQS queue

### ISSUE THREAD

**Issue by georgesbiaux** [Theodo-UK/sls-test-tools#14]
Hi :)

When calling the `getEvents` and that no message is present in the queue (because no events made is to EventBridge), instead of returning an empty array, or throwing a clear exception, I get:

```
    TypeError: Cannot read property 'length' of undefined
        at EventBridge.getEvents (/Users/georgesbiaux/Projects/Pyxo/pyxo/backend/node_modules/sls-test-tools/lib/helpers/eventBridge.js:101:25)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at Function.getAllEventBridgeMessages (/Users/georgesbiaux/Projects/Pyxo/pyxo/backend/tests/functions/utils/event-bridge.utils.ts:76:24)
        at Object.<anonymous> (/Users/georgesbiaux/Projects/Pyxo/pyxo/backend/tests/functions/deposit/createDepositCommand.test.ts:128:7)
```

When my test suite fails because an event has not been send correctly to EventBridge, it would be clearer if it was the assertion on the event that cause the failure :)

**Comment by valentinbeggi** [comment]
I believe this is fixed now, if there is no event the returned object contains at least ResponseMetadata with a requestId (and no Message)
